### ISSUE TITLE
Building of a Recommendations Tracking System

### ISSUE THREAD

**Issue by joaocarloscardoso** [joaocarloscardoso/AITAM#113]
Develop a new core module capable of publish as web page and track the the audit recommendations for the stakeholders. Key ideas:
- Requires the aggregation according to user criteria of audits and related recommendations and findings (concept of portfolio);
- Should be abble to integrate audits not coming from AITAM schemas (functionalities to create/edit?);
- May require persistence, obtained through JSON objects, stored in MONGODB, to obtain better presentation performance, and exports the porfolio definition, for later reuse, as an XML document;
- Reuses the provided credentials cto create and manage audits.

**Comment by joaocarloscardoso** [comment]
Requires for database: `npm install -save mongodb`

**Comment by joaocarloscardoso** [comment]
New libraries added:
- `portfolio.js`
- `db.js`

**Comment by joaocarloscardoso** [comment]
Methods to manage the portfolio document on `portfolio.js`:
- [ ] CreatePortfolioXML;
- [ ] VerifyPortfolioXML;
- [ ] GetPortfolioReferenceXML;
- [ ] SetPortfolioReferenceXML;
- [ ] DeleteAuditFromPortfolioXML;
- [ ] AddAuditToPortfolioXML;
- [ ] LoadPortfolioDataXML;

**Comment by joaocarloscardoso** [comment]
Methods to manage persistence data on `db.js`:
- [ ] SaveData

**Comment by joaocarloscardoso** [comment]
Started the interface:
- [ ] New top menu to present and manage recommendations (last on requires log in) in `nav.ejs`
- [ ] Page to present the portfolios (`recktracking.ejs`) and related partial: `partials/portfolios.ejs`

**Comment by joaocarloscardoso** [comment]
Redesign actions towards new and edit of portfolios:

- [ ] - Entry remains as original, focused on audit (creation and/or edit);
- [ ] - New portfolio open as a new and empty form, available at portfolio management page;
- [ ] - New action in portfolios' management table to download/export in XML format (as "delete..." hyperlink);
- [ ] - Availability of recommendations tracking system in application (visibility and access) is controlled through a parameter in `credentials.js` (`portfolio="Yes"|"no"`)
